#!/bin/bash -e
cd $(mktemp -d)

echo "Downloading Google Chrome (.deb package) ..."
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
dpkg -x google-chrome-stable_current_amd64.deb chrome/

echo "Unpacking Google Chrome ..."
cd chrome/
cp -a * /
[ ! -e /usr/share/pixmaps/google-chrome.png ] && \
    ln -s /opt/google/chrome/product_logo_256.png /usr/share/pixmaps/google-chrome.png
chmod 4755 /opt/google/chrome/chrome-sandbox

# An odd lib dependency...
[ ! -e /usr/lib/libudev.so.0 ] && ln -s libudev.so /usr/lib/libudev.so.0

rm -f /etc/cron.daily/google-chrome
